- .babelrc
- package-lock.json
- package.json
For React Testing Library and Styled components. Added plugin to babel config.
> Installed extra dependencies 

- client/src/components/App.jsx
- client/src/components/AppContext.jsx
- client/src/components/reviews/ReviewMain.jsx
- client/src/index.jsx
Updated:
- App.jsx with useContext setting
- AppContext.jsx
- reviews/ folder
- fixed some syntax error, please ignore the "never used" error in reviews/ folder for now.
TODO:
- set up your folder and files for component
- import your component in App.jsx
> Update useContext and folder settings

- client/src/components/App.jsx
- client/src/components/related_products/Lists/Outfit.jsx
- client/src/components/related_products/Lists/ProductList.jsx
- client/src/components/related_products/Lists/styles.jsx
- client/src/components/related_products/ProductCard/Card.jsx
- client/src/components/related_products/ProductCard/styles.jsx
- client/src/components/related_products/RelatedProductsMain.jsx
Created a blueprint for Lists and Product cards. Set up file structure and folders for styled components. Will make new branches after this to flesh out individual features.
> Wireframe of Lists & Product Cards

- .env
- client/src/components/App.jsx
- client/src/components/errorPage.jsx
- client/src/components/overview/OverviewMain.jsx
- client/src/components/overview/overview_components/Add.jsx
- client/src/components/overview/overview_components/QuantityList.jsx
- client/src/components/overview/overview_components/SizeList.jsx
- client/src/components/overview/overview_components/StylesList.jsx
- client/src/index.jsx
- package-lock.json
- package.json
- server/controllers.js
- server/index.js
- webpack.config.js
1) Added react-router-dom to webpack. 2) Added authorization to .env …
…3) Added file structure for overview components. 4)Added controllers.js 5)Added 2 handler functions for overview GET/POST requests 6) Added routes for 2 overview handler functions in index.js 7) Added temporary errorPage.jsx for possible react-router implementation. 8) Added significant functionality to overview components (NOT READY FOR REVIEW). This commit documents that all overview_components will need significant review for futurepull requests.
> Adding overview main

- server/controllers.js
- server/index.js
Updated with:
add request handler for '/reviews' and '/reviews/meta'
> Update: API requests handlers for reviews

- client/src/components/App.jsx
- client/src/components/overview/OverviewMain.jsx
- client/src/components/overview/overview_components/QuantityList.jsx
- client/src/components/overview/overview_components/SizeList.jsx
- client/src/index.jsx
Updates include:
1) Changed default product to a product with no erroneous data
2) Added updates to quantity dropdown list and made it visible. NOTE: THIS STILL HAS ERRORS. Much of the functionality works and on a a future request, a few small bugs will need to be fixed.
3) Updated sizes dropdown list to account for dependencies in quantity dropdown list. Functionality working as expected.
4) Updated main overview to account for changes in dropdown lists.
> Fixed multiples bugs involving dependencies of dropdown lists.

- client/src/components/reviews/Dropdown.jsx
- client/src/components/reviews/RatingSummary.jsx
- client/src/components/reviews/ReviewCard.jsx
- client/src/components/reviews/ReviewMain.jsx
- client/src/components/reviews/StarRating.jsx
- client/src/components/reviews/Thumbnail.jsx
- client/src/components/reviews/WriteReview.jsx
- client/src/components/reviews/styles.js
- A ReviewMain components as a layout map
- A RatingSummary breakdown component
- A Dropdown component for sorting
- A ReviewCard component for displayingreview details 
- An empty WriteReview form component
- A reusable modulized starRating component.
- A stylesheet for reviews module
> Update: review components

- .env
- client/src/components/App.jsx
- client/src/components/related_products/Lists/ProductList.jsx
- client/src/components/related_products/Lists/styles.jsx
- client/src/components/related_products/RelatedProductsMain.jsx
- server/controllers.js
- server/index.js
-Fixed some lingering issues with the carousel
-Created request handler functions to getProduct and getRelatedProducts
-Implemented dynamic product cards
-some bad data so I created some conditional rendering for a particular case(need to revisit)
-Refactored Card component to get default style and use that for the images and price
> List carousel + dynamic product cards

- server/controllers.js
- server/index.js
Updated with:
- New request handler for submitting a review, set review helpful, and report a review
- Updated the response code to restrict the error messages on server side
- Removed duplicated methods
- Updated the syntax following the eslint style guide (still have warnings for using console.error, but I believe they are necessary at this moment)
> Update: Request handlers

- client/src/components/App.jsx
- client/src/components/overview/OverviewMain.jsx
- client/src/components/overview/OverviewTests.js
- client/src/components/overview/overview_components/Add.jsx
- client/src/components/overview/overview_components/Description.jsx
- client/src/components/overview/overview_components/Price.jsx
- client/src/components/overview/overview_components/QuantityList.jsx
- client/src/components/overview/overview_components/StylesList.jsx
- client/src/components/overview/overview_components/stylesListStyling.js
The changes for this pull request include:
1) Updated Overview file structure (added files)
2) Updated Main file to account for file changes
3) Added initial css styles file for list component
4) Added testing file for overview components
5) Added price component and functionality
6) Fixed errors in add to cart button functionality (add.jsx)
> Updated file structure, added Price and Add functionality

- client/src/components/related_products/Lists/ProductList.jsx
- client/src/components/related_products/ProductCard/Card.jsx
- client/src/components/related_products/ProductCard/styles.jsx
- client/src/components/related_products/RelatedProductsMain.jsx
- client/src/components/reviews/RatingSummary.jsx
- Added dynamic stars reflecting the product's average rating to the product card using StarRating component from Reviews
- The app will now re-render when a product is clicked and this updates the product details and related products*
*there is a limit to how many clicks you can do in a short period before the API locks you out for too many requests. Approximately 6-7 GET requests per click.
> Clickable cards

- client/src/components/App.jsx
- client/src/components/globalStyling.js
- client/src/components/overview/OverviewMain.jsx
- client/src/components/overview/overview_components/Add.jsx
- client/src/components/overview/overview_components/ImageGalleryMain.jsx
- client/src/components/overview/overview_components/PhotoList.jsx
- client/src/components/overview/overview_components/QuantityList.jsx
- client/src/components/overview/overview_components/SizeList.jsx
- client/src/components/overview/overview_components/StylesList.jsx
- client/src/components/overview/overview_components/stylesListStyling.js
- package-lock.json
- package.json
Extensive updates:
1) Added shared global css file
2) Minor change to App file to account for global css
3) Added dependency in webpack for react dropdown list
4) Significant updates to Overview Add, SizeList, and OverviewMain to fix dependency bugs/errors and account for bad data. Functionality of these components is mostly complete. 
5) Added css file for Overview components
6) Image Gallery and photos main are not connected and can be safely ignored for now. No functionality has been implemented with these yet.
> Extensive updates

- client/src/components/reviews/Loading.jsx
- client/src/components/reviews/RatingSummary.jsx
- client/src/components/reviews/ReviewCard.jsx
- client/src/components/reviews/ReviewMain.jsx
- client/src/components/reviews/StarByProductId.jsx
- client/src/components/reviews/StarRating.jsx
- client/src/components/reviews/Thumbnail.jsx
- client/src/components/reviews/styles.js
- Finished request handlers on reviews components, and combined the handlers with buttons.
- Modified current styles.
- Modulized StartRating component that takes in a product id as a parameter, sends get request and renders star ratings.
- Fixed most of the eslint errors.
> Update: reviews requests and components

- client/src/components/reviews/ReviewMain.jsx
Fix the bug of unmatched data type.
> Update: add format converter in Reviews component

- client/src/components/App.jsx
- client/src/components/overview/OverviewMain.jsx
- client/src/components/overview/overview_components/ImageGalleryMain.jsx
- client/src/components/overview/overview_components/ImageMainStyles.js
- client/src/components/overview/overview_components/PhotoList.jsx
- client/src/components/overview/overview_components/SizeList.jsx
This update includes adding the main image feature and associated functionality.
> Image gallery

- client/src/components/overview/OverviewMain.jsx
- client/src/components/overview/overview_components/Add.jsx
- client/src/components/overview/overview_components/ImageGalleryMain.jsx
- client/src/components/overview/overview_components/ImageMainStyles.js
- client/src/components/overview/overview_components/ImageScroll.jsx
- client/src/components/overview/overview_components/Price.jsx
- client/src/components/overview/overview_components/QuantityList.jsx
- client/src/components/overview/overview_components/SizeList.jsx
- client/src/components/overview/overview_components/StylesList.jsx
Added image scroll feature and fixed many eslint errors.
> Added images scroll feature

- .eslintrc.js
- client/src/components/App.jsx
- client/src/components/overview/overview_components/Description.jsx
- client/src/components/overview/overview_components/ImageMainStyles.js
- client/src/errorPage.jsx
- client/src/index.jsx
- package-lock.json
- package.json
I've made some updates to shared files including webpack, App, and index. These were done to account for the addition of the React Router and an added error page file. Additionally, I've added a description feature including a modal for sharing on social media.
Lastly, I did notice a small modification to eslint involving jest. I believe we may need to update this to go back, as I can't remember the exact reasoning behind that update. Everything seems to be working, but I'll make a notice to update on the next push.
> Added react router basic structure in shared files, added description

- client/src/components/reviews/RatingSummary.jsx
- client/src/components/reviews/ReviewMain.jsx
- client/src/components/reviews/styles.js
- Now the average ratings and total rating numbers will be updated in global context when rendering.
- Fixed the star displaying bug.
- Added forward reference for review section
> Update: global context and reference

- client/src/components/App.jsx
- client/src/components/reviews/RadioButton.jsx
- client/src/components/reviews/RatingSummary.jsx
- client/src/components/reviews/ReviewMain.jsx
- client/src/components/reviews/StarRatingInput.jsx
- client/src/components/reviews/WriteReview.jsx
- client/src/components/reviews/styles.js
- server/controllers.js
- Complete the handlers and functions for writing a review
- Removed redundant code
- Put average ratings back into the global context
- Fixed bad request handler in controllers
> Complete write review functions

- client/src/components/reviews/ReviewMain.jsx
- client/src/components/reviews/StarByProductId.jsx
- client/src/components/reviews/WriteReview.jsx
- client/src/components/reviews/styles.js
- client/src/components/tests/DropDown.test.jsx
- client/src/components/tests/RadioButton.test.jsx
- client/src/components/tests/RatingSummary.test.jsx
- client/src/components/tests/ReviewCard.test.jsx
- client/src/components/tests/ReviewMain.test.jsx
- client/src/components/tests/WriteReview.test.jsx
Update test cases for review components
fixed the bugs in the testing procedure accordingly
> Update: 70% coverage test for reviews, fix bugs

- client/src/components/reviews/ReviewCard.jsx
- client/src/components/reviews/ReviewMain.jsx
- client/src/components/reviews/StarByProductId.jsx
- client/src/components/reviews/WriteReview.jsx
- client/src/components/reviews/styles.js
- client/src/components/tests/RatingSummary.test.jsx
- client/src/components/tests/ReviewCard.test.jsx
- client/src/components/tests/ReviewMain.test.jsx
Added more test cases for higher coverage and fixed some eslint errors
> Update: add more test cases and fix eslint

- client/src/components/App.jsx
- client/src/components/FooterStyles.js
- client/src/components/globalStyling.js
- client/src/components/reviews/styles.js
- Updated global settings for toggle themes
- Added a toggle button
> Update: toggle for day and night mode

- client/src/components/App.jsx
- client/src/components/Toggle.jsx
- client/src/components/related_products/Lists/styles.jsx
- client/src/components/related_products/ProductCard/Card.jsx
- client/src/components/related_products/ProductCard/styles.jsx
-Light mode/ Dark mode toggle
-Placeholder picture for products with no images
-Some minor css changes to my own component
> Theme toggle

- client/src/components/App.jsx
- client/src/components/overview/OverviewMain.jsx
- client/src/components/overview/imageGalleryComps/IconScroll.jsx
- client/src/components/overview/imageGalleryComps/ImageGalleryMain.jsx
- client/src/components/overview/imageGalleryComps/Magnifier.jsx
- client/src/components/overview/imageGalleryComps/PhotoListEntry.jsx
- client/src/components/overview/overviewStyles.js
- client/src/components/overview/productInfoAddComps/Description.jsx
- client/src/components/overview/productInfoAddComps/Stars.jsx
- client/src/components/overview/selectionComps/QuantityList.jsx
- client/src/components/overview/selectionComps/SizeList.jsx
- client/src/components/overview/selectionComps/StylesListEntry.jsx
I main a small change to App (updated default product).  Most of these other updates are CSS or some accessibility functionality.
> Updated CSS styling for new colors and dark mode. Added accessibility. 

- client/src/components/App.jsx
- client/src/components/Navbar.jsx
- client/src/components/Toggle.jsx
- client/src/components/globalStyling.js
- client/src/components/reviews/ReviewMain.jsx
- client/src/components/reviews/WriteReview.jsx
- client/src/components/reviews/styles.js
- Updated navbar style, added fake buttons
- Fixed reviews filter not working problem
- Updated form details
> Update navbar, fix reviews filter and form

- client/src/components/related_products/ProductCard/AddToOutfit.jsx
- client/src/components/related_products/ProductCard/Card.jsx
- client/src/components/related_products/ProductCard/styles.jsx
> minor update to add button

- README.md
- Bullet points of related product features
- added a gif for my widget
- added sections for the other widgets
> Completed readme for related products
